var languages = {
  'English'  : {
    'server_lang': 'english',
    'Info'       : 'Info',
    'History'    : 'History',
    'Traffic'    : 'Traffic',
    'Settings'   : 'Settings',
    'About'      : '?',
    
    'Billing URL'        : 'Billing URL',
    'Login'              : 'Login',
    'Password'           : 'Password',
    'Update every'       : 'Update every',
    'Remind about ending': 'Remaind about ending',
    'Remind if cash <'   : 'Remaind if cash <',
    'Always show cash'   : 'Always show cash',
    'Language'           : 'Language',
    'Data to show'       : 'Data to show',
    '1 hour'             : '1 hour',
    '3 hours'            : '3 hours',
    '6 hours'            : '6 hours',
    '12 hours'           : '12 hours',
    '24 hours'           : '24 hours',
    '1 day'              : '1 day',
    '3 days'             : '3 days',
    '7 days'             : '7 days',
    '14 days'            : '14 days',
    '21 days'            : '21 days',
    '1 month'            : '1 month',
    
    'Save'   : 'Save',
    'Refresh': 'Refresh',
    
    'Wrong URL': 'Wrong URL',
    'ERROR'    : 'ERROR',
    'by'       : 'by',
    'for'      : 'for',
    'till'     : 'till',
    
    'Name'          : 'Name',
    'User ID'       : 'User ID',
    'Address'       : 'Address',
    'Cash'          : 'Cash',
    'Last payment'  : 'Last payment',
    'Credit'        : 'Credit',
    'Credit expire' : 'Credit expire',
    'Reduction'     : 'Reduction',
    'Reduction date': 'Reduction date',
    'Contract'      : 'Contract',
    'Phone'         : 'Phone',
    'E-Mail'        : 'E-Mail',
    'IP'            : 'IP',
    'Plan'          : 'Plan',
    'State'         : 'State',
    'Expire date'   : 'Expire date',
    'Server time'   : 'Server time',
    'Message'       : 'Message',
    
    'Pay': "Add funds"
  },
  'Ukrainian': {
    'server_lang': 'ukraine',
    'Info'       : 'Інфо',
    'History'    : 'Історія',
    'Traffic'    : 'Трафік',
    'Settings'   : 'Опції',
    'About'      : '?',
    
    'Billing URL'        : 'Шлях до білінгу',
    'Login'              : 'Логін',
    'Password'           : 'Пароль',
    'Update every'       : 'Оновлювати кожні',
    'Remind about ending': 'Повідомляти за',
    'Remind if cash <'   : 'Повідомляти якщо гроші <',
    'Always show cash'   : 'Завжди показувати гроші',
    'Language'           : 'Мова',
    'Data to show'       : 'Данні що показуються',
    '1 hour'             : '1 година',
    '3 hours'            : '3 години',
    '6 hours'            : '6 годин',
    '12 hours'           : '12 години',
    '24 hours'           : '24 години',
    '1 day'              : '1 день',
    '3 days'             : '3 дня',
    '7 days'             : '7 днів',
    '14 days'            : '14 днів',
    '21 days'            : '21 день',
    '1 month'            : '1 місяць',
    
    'Save'   : 'Зберегти',
    'Refresh': 'Оновити',
    
    'Wrong URL': 'Неправильний шлях',
    'ERROR'    : 'ПОМИЛКА',
    'by'       : 'від',
    'for'      : 'для',
    'till'     : 'до',
    
    'Name'          : 'Ім’я',
    'User ID'       : 'Номер користувача',
    'Address'       : 'Адреса',
    'Cash'          : 'Гроші',
    'Last payment'  : 'Крайня оплата',
    'Credit'        : 'Кредит',
    'Credit expire' : 'Кредит до',
    'Reduction'     : 'Знижка',
    'Reduction date': 'Знижка до',
    'Contract'      : 'Угода',
    'Phone'         : 'Телефон',
    'E-Mail'        : 'Скринька',
    'IP'            : 'IP',
    'Plan'          : 'Тариф',
    'State'         : 'Стан',
    'Expire date'   : 'Активний до',
    'Server time'   : 'Час на сервері',
    'Message'       : 'Повідомлення',
    
    'Pay': "Поповнити рахунок"
  },
  'Russian'  : {
    'server_lang': 'russian',
    'Info'       : 'Инфо',
    'History'    : 'История',
    'Traffic'    : 'Трафик',
    'Settings'   : 'Опции',
    'About'      : '?',
    
    'Billing URL'        : 'Адрес билинга',
    'Password'           : 'Пароль',
    'Update every'       : 'Период обновления',
    'Remind about ending': 'Напоминать за',
    'Remind if cash <'   : 'Напоминать если баланс <',
    'Always show cash'   : 'Всегда показывать баланс',
    'Language'           : 'Язык',
    'Data to show'       : 'Показывать',
    '1 hour'             : '1 час',
    '3 hours'            : '3 часа',
    '6 hours'            : '6 часов',
    '12 hours'           : '12 часов',
    '24 hours'           : '24 часа',
    '1 day'              : '1 день',
    '3 days'             : '3 дня',
    '7 days'             : '7 дней',
    '14 days'            : '14 дней',
    '21 days'            : '21 день',
    '1 month'            : '1 месяц',
    
    'Save'   : 'Сохранить',
    'Refresh': 'Обновить',
    
    'Wrong URL': 'Ошибка адреса',
    'ERROR'    : 'Ошибка',
    'by'       : 'от',
    'for'      : 'для',
    'till'     : 'до',
    
    'Name'          : 'Имя',
    'Login'         : 'Логин',
    'User ID'       : 'Номер пользователя',
    'Address'       : 'Адрес',
    'Cash'          : 'Баланс',
    'Last payment'  : 'Последняя оплата',
    'Credit'        : 'Кредит',
    'Credit expire' : 'Кредит до',
    'Reduction'     : 'Скидка',
    'Reduction date': 'Скидка до',
    'Contract'      : 'Соглашение',
    'Phone'         : 'Телефон',
    'E-Mail'        : 'E-Mail',
    'IP'            : 'IP',
    'Plan'          : 'Тариф',
    'State'         : 'Состояние',
    'Expire date'   : 'Активен до',
    'Server time'   : 'Время сервера',
    'Message'       : 'Сообщение',
    'Pay'           : "Пополнить счёт"
  }
};

/*
 * Return outerHTML for the first element in a jQuery object,
 * or an empty string if the jQuery object is empty;
 */
jQuery.fn.outerHTML = function () {
  return (this[0]) ? this[0].outerHTML : '';
};
